version: '3'

services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  dashboard:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
      - WALLET=35eS5Lsqw8NCjFJ8zhp9JaEmyvLDwg6XtS
      - POWER_COST=0
      - POWER_USAGE=0
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis

volumes:
  redis_data: