version: '3'

services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 5s
      retries: 3
      start_period: 1s

  dashboard:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
      - WALLET=35eS5Lsqw8NCjFJ8zhp9JaEmyvLDwg6XtS
      - POWER_COST=0
      - POWER_USAGE=0
      - NETWORK_FEE=0
      - TIMEZONE=America/Los_Angeles
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 5s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
