name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Install Node dependencies
      run: npm ci
    - name: Build assets
      run: make minify
    - name: Run ruff
      run: ruff check .
    - name: Run tests
      run: pytest -q
